/*
Attuid:  kr1169
Project : NEXXUS
*/
CREATE TABLE NX_SOLUTION_DETAILS
(
  NX_SOLUTION_ID       NUMBER(11)               NOT NULL,
  OPTY_ID              VARCHAR2(30 BYTE)        NOT NULL,
  L3_VALUE             VARCHAR2(30 BYTE),
  L4_VALUE             VARCHAR2(30 BYTE),
  DUNS_NUMBER          VARCHAR2(15 BYTE),
  GU_DUNS_NUMBER       VARCHAR2(15 BYTE),
  CUSTOMER_NAME        VARCHAR2(55 BYTE),
  NXS_DESCRIPTION      VARCHAR2(55 BYTE),
  CREATED_USER         VARCHAR2(30 BYTE),
  CREATED_DATE         DATE                     NOT NULL,
  MODIFIED_USER        VARCHAR2(30 BYTE),
  MODIFIED_DATE        DATE                     NOT NULL,
  ACTIVE_YN            VARCHAR2(2 BYTE)         NOT NULL,
  IS_PRY_MVG           VARCHAR2(2 BYTE),
  L_NAME               VARCHAR2(55 BYTE),
  F_NAME               VARCHAR2(55 BYTE),
  SALES_REP_FULL_NAME  VARCHAR2(55 BYTE),
  EMAIL                VARCHAR2(55 BYTE),
  SALES_REP            VARCHAR2(55 BYTE),
  MANAGER_NAME         VARCHAR2(55 BYTE),
  MANAGER_HRID         VARCHAR2(30 BYTE),
  PRODUCT_CD           VARCHAR2(30 BYTE)
)
/
ALTER TABLE NX_SOLUTION_DETAILS ADD (
  CONSTRAINT NX_SOLUTION_DETAILS_PK
  PRIMARY KEY
  (NX_SOLUTION_ID)
  USING INDEX NX_SOLUTION_DETAILS_PK
  ENABLE VALIDATE)
/